
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
climate: !include climate.yaml
remote: !include remote.yaml
vacuum: !include vacuum.yaml

webhook:
zigbee2mqtt_networkmap:
   #topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
   networkmap:
     title: 'Zigbee Map'
     url: '/local/community/zigbee2mqtt_networkmap/map.html'
     icon: 'mdi:graphql'

frontend:
  themes: !include themes.yaml

homeassistant:
  customize: !include customize.yaml
  
sensor:
 - platform: template
    sensors:
      vacuum_status:
        friendly_name: Status
        entity_id:
          - vacuum.odkurzacz
        value_template: 'Status: {{ states.vacuum.odkurzacz.attributes.status }}'
        icon_template: >
          {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.status  %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_fan_speed:
          friendly_name: Fan Speed
          entity_id:
            - vacuum.odkurzacz
          value_template: 'Mode: {{ states.vacuum.odkurzacz.attributes.fan_speed }}'
          icon_template: 'mdi:speedometer'
      vacuum_battery:
          friendly_name: Vacuum Battery
          entity_id:
            - vacuum.odkurzacz
          value_template: 'Battery: {{ states.vacuum.odkurzacz.attributes.battery_level }}'
          unit_of_measurement: '%'
          icon_template: '{{ states.vacuum.odkurzacz.attributes.battery_icon }}'
      vacuum_cleaning_time:
          friendly_name: Time of Last Cycle
          entity_id:
            - vacuum.odkurzacz
          value_template: '{{ states.vacuum.odkurzacz.attributes.cleaning_time }}'
          icon_template: 'mdi:timer'
     vacuum_cleaned_area:
          friendly_name: Area of Last Cycle
          unit_of_measurement: 'm ²'
          entity_id:
            - vacuum.odkurzacz
          value_template: '{{ states.vacuum.odkurzacz.attributes.cleaned_area }}'
          icon_template: 'mdi:ruler'
      vacuum_cleanmainbrush:
          friendly_name: Replace main brush
          unit_of_measurement: 'h'
          entity_id:
            - vacuum.odkurzacz
          value_template: 'Main Brush: {{ states.vacuum.odkurzacz.attributes.main_brush_left }}'
          icon_template: 'mdi:screwdriver'
      vacuum_cleansidebrush:
          friendly_name: Replace side brush
          unit_of_measurement: 'h'
          entity_id:
            - vacuum.odkurzacz
          value_template: 'Side brush: {{ states.vacuum.odkurzacz.attributes.side_brush_left }}'
          icon_template: 'mdi:screwdriver'
      vacuum_cleanfilter:
          friendly_name: Replace filter
          unit_of_measurement: 'h'
          entity_id:
            - vacuum.odkurzacz
          value_template: 'Filter: {{ states.vacuum.odkurzacz.attributes.filter_left }}'
          icon_template: 'mdi:screwdriver'
      vacuum_sensordirtyleft:
          friendly_name: Replace filter
          unit_of_measurement: 'h'
          entity_id:
            - vacuum.odkurzacz
          value_template: 'Sensor: {{ states.vacuum.odkurzacz.attributes.sensor_dirty_left }}'
          icon_template: 'mdi:screwdriver'
      vacuum_do_not_disturb:
          friendly_name: Do Not Disturb
          entity_id:
            - vacuum.odkurzacz
          value_template: '{{ states.vacuum.odkurzacz.attributes.do_not_disturb }}'
          icon_template: >
            {% set val =  states.vacuum.odkurzacz.attributes.do_not_disturb  %}
            {% if val == 'on' %}
             mdi:do-not-disturb
            {% endif %}
      vacuum_operation:
          value_template: 'Operacje'
      vacuum_accessories:
          value_template: 'Zużycie'
